# Mode 2 prevents overcommitment.
# The kernel tries to ensure that the sum of the memory allocations requested by all processes.
# does not exceed the available physical memory and swap space.
# When a process requests memory in excess of the available resources, the allocation request is denied,
# and the process is usually notified with an error

vm.overcommit_memory = 2
vm.overcommit_ratio = 95
