#!/bin/sh

OLD_FINGERPRINT=/opt/unipi/os-configurator/fingerprint

if [ "$1" = "--check" ]; then
    echo "OS Configurator: check started" > /dev/kmsg
    FG="$(/opt/unipi/tools/unipiid fingerprint)"
    OFG="$(cat ${OLD_FINGERPRINT})"
    #logger FG=$FG OFG=$OFG
    
    if [ "$(/opt/unipi/tools/unipiid fingerprint)" = "$(cat ${OLD_FINGERPRINT})" ]; then

        echo "OS Configurator: Check complete, no changes" > /dev/kmsg
        exit 0
    fi

    echo "OS Configurator: Changes found, calling update..." > /dev/kmsg
    shift

fi
if [ "$1" = "--update" ]; then
    echo "OS Configurator: Update invoked" > /dev/kmsg
    if python3 /opt/unipi/os-configurator/os-configurator.py $*; then
        /opt/unipi/tools/unipiid fingerprint > "${OLD_FINGERPRINT}"
        echo "Reboot system to apply all changes in configuration"
        sync
        mount / -o remount,ro
        #sleep 2;
        sync
        systemctl start reboot.target --job-mode=replace-irreversibly --no-block
        #systemctl reboot
    fi
    exit $?
fi
if [ "$1" = "--force" ]; then
    if python3 /opt/unipi/os-configurator/os-configurator.py $*; then
        /opt/unipi/tools/unipiid fingerprint > "${OLD_FINGERPRINT}"
    else
        rm -f "${OLD_FINGERPRINT}"
    fi
    echo "Reboot system to apply all changes in configuration"
    exit 0
fi
exec python3 /opt/unipi/os-configurator/os-configurator.py $*
