#!/bin/sh

# try to reconfigure network interfaces managed by networkctl
#
# use after changing hostname to recall dhcp request with new name
#

ETHS=$(networkctl list | awk '/ configured$/ || / configuring$/ {printf $2 " " ;}')
if [ -n "${ETHS}" ]; then
    networkctl reconfigure ${ETHS}
fi

systemctl --no-block try-restart avahi-daemon 2> /dev/null || true
